# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# The color e.g. of an object or of a light like RGB LED, OLED, ...

std_msgs/Header header  # stamp is the time the color was measured.
                        # frame_id is the location of the measurement (does not need to be TF frame, but it is recommended).
std_msgs/ColorRGBA value  # The color.
